### ISSUE TITLE
Can not find the module FixedPointImplementation

### ISSUE THREAD

**Issue by ColsonZhang** [nimish15shah/GRAPHOPT#1]
Hi, I'm very interested in this work and tried to run the code. However, I found that I can not import FixedPointImplementation. So is it an additional module which is not included in this project?

**Comment by nimish15shah** [comment]
Hi Colson, 

Thank you for pointing out the error. This is fixed in the latest commit.

Thanks,
Nimish

**Comment by ColsonZhang** [comment]
Thank you very much !
By the way, I am also doing the research of accelerating the spn by designing the heterogeneous hardware. I have read most of your papers which are good jobs !

**Comment by nimish15shah** [comment]
Oh, good to hear that! Look forward to your work. If you want to discuss anything from the papers, feel free to reach me at nimish.shah@esat.kuleuven.be
