### ISSUE TITLE
Can you give me hint on how to get psdd file?

### ISSUE THREAD

**Issue by Sungwoo-Ahn** [nimish15shah/GRAPHOPT#2]
Hi I'm trying to study this DAG optimization topic and having problem running your github.

I followed all the minizinc instructions and dependencies but I couldn't fine the input file.
I tried several ways to find PSDD file from websites but I couldn't find the one.
Can you give me hint on how to get psdd file?

I also tried to modify the global_var.py file.
I'm sorry I'm new to this area, so can you give me more instructions on how to add the file names in refresh function?

**Comment by nimish15shah** [comment]
Hi Sungwoo-Ahn,

The repository was indeed not fully clean for running a bare-minimum example. I cleaned up the files and added the basic psdd and sprase matrix workloads form the UCLA StarAI circuit-zoo and SuiteSparse matrix collection.

Could you please try running the following command?:
python main.py --tmode psdd_full --net mnist

If the Google OR-Tools dependency is installed, this command should run without any error.

The script does not produce any files yet. I am cleaning up the rest of the flow, which will eventually allow you to execute the DAG superlayers with openMP.

**Comment by Sungwoo-Ahn** [comment]
Hi Nimish,

Thank you for the fast feedback!
Your command worked and the last output on terminal is
"INFO:graph_analysis:edge_crossing : 161"
I assume that this is working!
